### ISSUE TITLE
Compilation error fix.

### ISSUE THREAD

**Issue by johste93** [QThund/LineRenderer2D#2]
To make this work in Unity 2021.3 I had to replace all instances of

```
if (_IsUnlit == 0.0f)
{
    // Lighting
    finalColor = CombinedShapeLightShared(finalColor, maskColor, i.screenPos);
}
```

with:

```
if (_IsUnlit == 0.0f)
{
    // Lighting
    SurfaceData2D surfaceData;
    InputData2D inputData;
    surfaceData.albedo = finalColor.rgb;
    surfaceData.alpha = 1;
    surfaceData.mask = maskColor;
    inputData.uv = i.screenPos;
    finalColor = half4(CombinedShapeLightShared(surfaceData, inputData).rgb, finalColor.a);
}
```

**Comment by GabrielBigardi** [comment]
Shader error in 'Game/S_BresenhamMultiLineRenderer2D': variable 'inputData' used without having been completely initialized at line 156 (on d3d11)

**Comment by StinkySteak** [comment]
Not sure if this fixes it, but I used `ZERO_INITIALIZE(InputData2D, inputData);` before `inputData.uv = i.screenPos;`

**Comment by StinkySteak** [comment]
just added a new fork & pull request for anyone required to use unity 2021.3

**Comment by M0Z1NG0** [comment]
Ah, thanks. I used the initialize functions, but this did the trick. Using 2022.3.10f1
```
SurfaceData2D surfaceData;
InputData2D inputData;
InitializeSurfaceData(finalColor.rbg, finalColor.a, maskColor, surfaceData);
InitializeInputData(i.screenPos, inputData);
finalColor = CombinedShapeLightShared(surfaceData, inputData);
```
